#!/bin/bash

set -e

emacs --batch -l shannon-max.el -l shannon-max-test.el -f ert-run-tests-batch-and-exit

emacs --batch --eval "(setq byte-compile-error-on-warn t)" -f batch-byte-compile "shannon-max.el"
